server:
  port: 8080

ai:
  service:
    mode: real 
    
spring:
  ai:
    ollama:
      base-url: http://ollama:11434
      chat:
        model: llama3
        
  # cache:
  #   type: redis
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/project_realization}
    username: ${SPRING_DATASOURCE_USERNAME:project_realization}
    password: ${SPRING_DATASOURCE_PASSWORD:project_realization}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: project-realization-service

#redis:
#  host: ${REDIS_HOST:localhost}
#  port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true
    
jwt:
  secret: ${JWT_SECRET:c3Rha2Vob2xkZXJzZXJ2aWNland0c2VjcmV0a2V5Zm9ydGgyNTZiaXRzMTIzNDU2Nzg5MA==}
