spring:
  application:
    name: document-management-service
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://document-postgres:5432/documents}
    username: ${SPRING_DATASOURCE_USERNAME:document}
    password: ${SPRING_DATASOURCE_PASSWORD:document}
  jpa:
    hibernate:
      ddl-auto: update

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
