server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ProjectRealizationService
          uri: lb://project-realization-service
          predicates:
            - Path=/project-realization-service/**
          filters:
            - StripPrefix=1
        - id: ProjectRealizationAnalyticsService
          uri: lb://project-realization-analytics-service
          predicates:
            - Path=/project-realization-analytics-service/**
          filters:
            - StripPrefix=1
        - id: StakeholderService
          uri: lb://stakeholder-service
          predicates:
            - Path=/stakeholder-service/**
          filters:
            - StripPrefix=1
        - id: PromptVectorService
          uri: lb://prompt-vector-service
          predicates:
            - Path=/prompt-vector-service/**
        - id: doucument-management-service
          uri: lb://doucument-management-service
          predicates:
            - Path=/doucument-management-service/**
          filters:
            - StripPrefix=1