spring.application.name=timeseries-database-service
spring.influx.url=${INFLUX_URL:http://localhost:8086}
spring.influx.token=${INFLUX_TOKEN:}
spring.influx.org=${INFLUX_ORG:}
spring.influx.bucket=${INFLUX_BUCKET:document_management}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

server.port=8082
